### ISSUE TITLE
Run all tests before allowing an npm publish

### ISSUE THREAD

**Issue by jwulf** [camunda-community-hub/zeebe-client-node-js#190]
At the moment npm publish builds the source, but doesn't run the test suite. A broken package could be released like this. Run the tests before publishing.

**Comment by VoidCupboard** [comment]
Can I work on this issue? This issue doesn't seem to be fixed yet

**Comment by jwulf** [comment]
This has been fixed. We now publish via a GitHub Action that runs the tests. Thanks for the offer @VoidCupboard.
