### ISSUE TITLE
Support Zeebe 1.0.0

### ISSUE THREAD

**Issue by jwulf** [camunda-community-hub/zeebe-client-node-js#208]
Zeebe 1.0.0 is coming out, with a breaking API change. Work is in progress in the 1.0.0 branch.

See [here](https://forum.zeebe.io/t/changelog-for-zeebe-client-lib-maintainers/2064) for more details.

**Comment by barmac** [comment]
Hey Josh, I'd like to support you with 1.0.0 release. How can I help?

**Comment by jwulf** [comment]
New version out to support the latest alpha of Zeebe: https://www.npmjs.com/package/zeebe-node/v/1.0.0-alpha.7

**Comment by jwulf** [comment]
Changes merged for 1.3.0.
