### ISSUE TITLE
Excessive pings error

### ISSUE THREAD

**Issue by jwulf** [camunda-community-hub/zeebe-client-node-js#262]
Running 8.0.1 of the zeebe-client-node against 8.0.2 of Zeebe triggers this error each time the app comes up:

```
stderr E Connection to dns:camunda8-zeebe-gateway:26500 at 172.20.40.118:26500 rejected by server because of excess pings. Increasing ping interval to 180000 ms
```

**Comment by jwulf** [comment]
This is most probably due to either `grpc.keepalive_time_ms` or `grpc.http2.min_time_between_pings_ms` setting in [src/lib/GrpcClient.ts](https://github.com/camunda-community-hub/zeebe-client-node-js/blob/master/src/lib/GrpcClient.ts). 

Making these configurable via env vars and constructor will be the way to go.

**Comment by dknapp47** [comment]
Reproducer did not reproduce it on my Macbook either. I have also packaged the reproducer in a docker container and run it like we run our app. That also did not reproduce it. I will try more things tomorrow.

**Comment by dknapp47** [comment]
Just a quick update. We still see this message sporadically and continue to try to find the pattern to reproduce it.

**Comment by jwulf** [comment]
Any further observations of this @dave-apex?

**Comment by dave-apex** [comment]
@jwulf Apologies for the delayed response. We have been focused on other projects and have not had time to come back to this to try to zero in on the problem.

**Comment by jwulf** [comment]
Closing this over here. If it is an issue with the new client and affects users, we will open an issue over here: https://github.com/camunda-community-hub/camunda-8-js-sdk/issues
