### ISSUE TITLE
fetchVariable does not have effect on job workers

### ISSUE THREAD

**Issue by Veckatimest** [camunda-community-hub/zeebe-client-node-js#264]
There is a createWorker method of zbClient.
It uses this configuration:
```
export interface ZBWorkerOptions<InputVars = IInputVariables> {
	maxJobsToActivate?: number
        // ... other fields
	fetchVariable?: (keyof InputVars)[]
}
```

## Expected Behavior
When I use fetchVariable option, I only receive specified variables in my job executor.

## Current Behavior
I receive all variables
## Possible Solution
Feels like library uses `ActivateJobRequest` from [src/lib/interfaces-grpc-1.0.ts](https://github.com/camunda-community-hub/zeebe-client-node-js/blob/master/src/lib/ZBWorkerBase.ts#L518) to fetch jobs.

And there is `activateJobs` method in the ZBWorkerBase.ts, that fetches jobs.
```
// some code
		const activateJobsRequest: ActivateJobsRequest = {
			maxJobsToActivate: amount,
			requestTimeout,
			timeout: this.timeout,
			type: this.taskType,
			worker: this.id,
		}
```
This request does not have fetchVariable in it, so I guess this is the problem (but the type [does](https://github.com/camunda-community-hub/zeebe-client-node-js/blob/master/src/lib/interfaces-grpc-1.0.ts#L30))
 

## Steps to Reproduce
1. create a worker
2. add fetchVariable
3. check what variables you received

**Comment by jwulf** [comment]
This is fixed in 8.0.3 of the client library.
