### ISSUE TITLE
How to connector to zeebe gateway without config port

### ISSUE THREAD

**Issue by gogroup-official** [camunda-community-hub/zeebe-client-node-js#310]
My zeebe gateway goes through a proxy and has an endpoint of zeebe.xxx.com/gateway.
by default zeebe node will insert port 26500 leading to connection failure.
`| zeebe |  [worker-1] ERROR: Grpc Stream Error: 14 UNAVAILABLE: Name resolution failed for target dns:zeebe.xxx.com/gateway:26500 - zeebe.xxx.com/gateway:26500`
Is there any solution to fix this?
i just want to configure hostname

**Comment by jwulf** [comment]
From the [test suite](https://github.com/camunda-community-hub/zeebe-client-node-js/blob/master/src/__tests__/ZBClient.spec.ts#L22):

```
test('ZBClient constructor appends the port number 26500 to the gatewayAddress by default', () => {
	const zbc = new ZBClient('localhost')
	expect(zbc.gatewayAddress).toBe('localhost:26500')
	zbc.close()
})
test('ZBClient constructor accepts a custom port number for the gatewayAddress', () => {
	const zbc = new ZBClient('localhost:123')
	expect(zbc.gatewayAddress).toBe('localhost:123')
	zbc.close()
})
```
