### ISSUE TITLE
Retry backoff best practice 

### ISSUE THREAD

**Issue by ryanelee** [camunda-community-hub/zeebe-client-node-js#315]
Just try to understand the `retryBackoff` feature for failing a job mentioned [here](https://github.com/camunda-community-hub/zeebe-client-node-js#completing-tasks-with-success-failure-error-or-forwarded):

- Once specifying the `retryBackoff` in `job.fail`, will the backoff be managed by Camunda automatically and there isn't any logic needed in our application? Which means if a job fails with a given 5 minutes retryBackoff, the job will be hidden for [Activate Jobs](https://github.com/camunda-community-hub/zeebe-client-node-js#activate-jobs) or [Job Worker](https://github.com/camunda-community-hub/zeebe-client-node-js#job-workers) until the 5 minutes is elapsed?
- Similar as the `retries`, is there a way to get the assigned value of the `retryBackoff`? Couldn't find it thru Camunda Operate portal or [ActivateJob gRPC](https://docs.camunda.io/docs/apis-tools/grpc/#activatejobs-rpc). 
- Is there a best practice recommended for implementing the [exponential backoff](https://en.wikipedia.org/wiki/Exponential_backoff) with Zeebe?

**Comment by jwulf** [comment]
Hi @ryanelee, 

Thanks for using the Zeebe Node client!

This question is best asked in the [Camunda 8 Slack](https://camunda.com/slack) or in the [Camunda Forums](https://forum.camunda.io). It spans both the client and the broker. 

Please use the issue tracker for reporting bugs in the client library.
