### ISSUE TITLE
Worker job fail command reduces retries to 0 even when indicating 3

### ISSUE THREAD

**Issue by patozgg** [camunda-community-hub/zeebe-client-node-js#316]
Issue tracker is **ONLY** used for reporting bugs. New features and questions should be discussed on [our slack channel](https://www.camunda.com/slack).

## Expected Behavior
I am using the following command in my worker (https://github.com/camunda-community-hub/zeebe-client-node-js#connection-behaviour)

		job.fail({
			errorMessage: 'Triggering a retry with a thirty second back-off',
			retryBackOff: 30000,
			retries: 3,
		})
which as per the documentation the retries should stay at 3 as I am providing a value. However,  after running such code the retries go down to 0 and an incident is created. 

## Current Behavior
Retries get reduced to zero and an incident is created. Instead I would expect the retries to stay at 3. 

## Steps to Reproduce

1. Have Camunda 8 environment running
2. Setup worker with the job fail command
3. Setup BPMN with service task
4. Run worker and process

## Context (Environment)
I am using version 8.2.3 of https://github.com/camunda-community-hub/zeebe-client-node-js#connection-behaviour and version 8.2.5 of Camunda 8.

**Comment by jwulf** [comment]
Version 8.2.3 is published with this fix in it: https://www.npmjs.com/package/zeebe-node
